fetch_vehicle_info:
  description: >
    Respond to the user with detailed, friendly information about features and pricing of the user's choice of vehicle.
  expected_output: >
    "The car comes with features like [list features]. The base model starts at $XYZ. Is there anything else you'd like to know?"
  agent: researcher_agent
  human_input: true

analyze_data:
  description: >
    Provide insights in a conversational way about features like the retractable rear window or pricing details.
  expected_output: >
    "The car does have a retractable rear window, and the pricing is as follows: [details]. Would you like more information?"
  agent: analyst_agent
  human_input: true

customer_interaction:
  description: >
    Engage the user with friendly questions or answers to assist in their purchasing decision.
  expected_output: >
    "That's great to hear! What other details would you like to know before making your decision?"
  agent: sales_agent
  human_input: true

process_payment:
  description: >
    Guide the user through the payment process conversationally.
  expected_output: >
    "Thank you for your purchase! Let me guide you through the payment process. Which payment method would you like to use?"
  agent: accounting_agent
  human_input: true